#!/command/with-contenv sh
set -e

export NGINX_SERVER_NAME="${NGINX_SERVER_NAME:-localhost}"
export SSL_CERTIFICATE_FILE="${SSL_CERTIFICATE_FILE:-/nginx-cert.pem}"
export SSL_CERTIFICATE_KEY_FILE="${SSL_CERTIFICATE_KEY_FILE:-/nginx-key.pem}"

TEMPLATE="${NGINX_TEMPLATE:-/etc/nginx/templates/base.conf.template}"

envsubst '${NGINX_SERVER_NAME} ${SSL_CERTIFICATE_FILE} ${SSL_CERTIFICATE_KEY_FILE}' \
  < "${TEMPLATE}" \
  > /etc/nginx/conf.d/default.conf

exec nginx -g 'daemon off;'
